routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('topics', 'TopicController');
Route::resource('questions', 'QuestionController');
Route::resource('results', 'ResultsController');
Route::resource('adminpanel', 'AdminPanelController');
Route::resource('questionsOptions', 'QuestionsOptionsController');
Route::resource('users', 'UserController');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    //

    protected $table = 'topics';
    protected $fillable = ['title', 'no_question', 'duration'];

    public function questions() {
        return $this->hasMany('App\Question', 'topic_id', 'id');
    }

}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTopicRequest;
use App\Http\Requests\UpdateTopicRequest;
use App\Question;
use App\Topic;
use Illuminate\Http\Request;
use DateTime;
use Carbon\Carbon;

class TopicController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
        $this->middleware('admin')->except(['index', 'show']);


    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $topics = Topic::all();

        return view('topics.index', ['topics' => $topics]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        $topics = Topic::all();

        return view('topics.create', ['topics'=>$topics]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTopicRequest $request)
    {
        //


        $topic= Topic::create([
            'title' => $request->title,
            'no_question' => $request->question,
            'duration' => $request->duration


        ]);


        return redirect(route('topics.index'));
    }





    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        //

        $topic = Topic::findOrFail($id);

        $time = $topic->duration;



        return view('topics.show', ['topic' => $topic, 'time'=>$time]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $topic = Topic::find($id);

        return view('topics.edit', ['topic'=>$topic]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTopicRequest $request, $id)
    {
        //
        $topic = Topic::find($id);
        $topic->title = $request->input('title');
        $topic->save();

        return redirect(route('topics.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $topic = Topic::find($id);
        $topic->delete();

        return redirect(route('topics.index'));
    }
}

resources/views/topics/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            <h2 align="center">Create new Quiz</h2>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="form-group">
                <form action="{{route('topics.store')}}" method="post">
                    @csrf
                    <div class="form-group">
                        <input type="text" name="title" class="form-control" placeholder="title">
                    </div>
                    <div class="form-group">
                        <input type="text" name="question" class="form-control" placeholder="No of questions">
                    </div>
                    <div class="form-group">
                        <input type="text" name="duration" class="form-control" placeholder="duration">
                    </div>
                    <input type="submit" name="submit" id="submit" class="btn btn-info" value="Create Topic"/>
                </form>
            </div>

           
@endsection

resources/views/topics/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if($topic)
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-12">
                <h1>{{$topic->title}}</h1>
                <div class="form-group">
                    <form action="{{route('topics.update', $topic->id)}}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <input required type="text" name="title" class="form-control" value="{{$topic->title}}">
                        </div>
                        <div class="form-group">
                            <input required type="text" name="question" class="form-control" value="{{$topic->no_question}}">
                        </div>
                        <div class="form-group">
                            <input required type="text" name="duration" class="form-control" value="{{$topic->duration}}">
                        </div>
                        <input type="submit" name="submit" id="submit" class="btn btn-info" value="Edit Topic">
                    </form>
                </div>
            </div>
            @else
                <h1>No Topic</h1>
            @endif
        </div>
        </div>
    </div>
@endsection

resources/views/topics/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @if(Auth::user())
            @if(Auth::user()->role == 'admin')
                @include('adminpanel.adminSidebar')
            @endif
        @endif
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-4">
                    <h3 class="page-title">Topics</h3>
                    @foreach($topics as $topic)
                        <div class="card">
                            <div class="card-body mb-6">
                                <h5 class="card-title">{{$topic->title}}</h5>
                                <a href="{{route('topics.show', $topic->id)}}" class="inline_block btn btn-primary">Go
                                    To Quiz</a>
                                @if(Auth::user())
                                    @if(Auth::user()->role == 'admin')
                                        <a href="{{route('topics.edit', $topic->id)}}"
                                           class="inline_block btn btn-warning">Edit</a>
                                        <form class="inline_block" action="{{route('topics.destroy', $topic->id)}}"
                                              method="post">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                                        </form>
                                    @endif
                                @endif
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/topics/show.blade.php
@extends('layouts.app')

@section('script')

<!-- script for time limitation of exam -->
<script type="text/javascript">
var timeoutHandle;
function countdown(minutes) {
    var seconds = 60;
    var mins = minutes
    function tick() {
        var counter = document.getElementById("timer");
        var current_minutes = mins-1
        seconds--;
        counter.innerHTML =
        current_minutes.toString() + ":" + (seconds < 10 ? "0" : "") + String(seconds);
        if( seconds > 0 ) {
            timeoutHandle=setTimeout(tick, 1000);
        } else {
            if(mins > 1){
               // countdown(mins-1);   never reach “00″ issue solved:Contributed by Victor Streithorst
               setTimeout(function () { countdown(mins - 1); }, 1000);
            }
        }
    }
    tick();
}
countdown('<?php echo $time; ?>');
</script>

<!-- script for disable url -->
<script type="text/javascript">
    var time= '<?php echo $time; ?>';
    var realtime = time*60000;
    setTimeout(function () {
        alert('Time Out');
        window.location.href= '/';},
   realtime);

</script>

@endsection
@section('content')
    <div class="container">
        @if($topic)
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row">
                <div class="col-md-12">
                    <h1><b>Time <span id="timer" style="color: red">0.00</span></b></h1><br>
                    <h1>{{$topic->title}}</h1>
                    <form action="{{route('results.store')}}" method="post">
                        @csrf
                        <div>
                            <input type="hidden" name="duration" value="{{$topic->duration}}">

                            <input type="hidden" name="topic_id" value="{{$topic->id}}">
                            @foreach($topic->questions as $question )
                                <div>
                                    {{$question->question_text}}
                                    <input type="hidden" name="question_id[]" value="{{$question->id}}">
                                    @foreach($question->options as $option)
                                        <div>
                                            <input type="checkbox" name="option[{{$question->id}}][{{$option->id}}]"
                                                   value="{{$option->correct}}">
                                            {{$option->option}}
                                        </div>
                                    @endforeach
                                </div>
                            @endforeach
                        </div>
                        <a href="{{route('results.show', $topic->id)}}"><input type="submit" value="Submit"
                                                                               class="btn btn-success mt-3"></a>
                    </form>
                </div>
            </div>
        @else
            <h1>No Topic</h1>
        @endif
    </div>



@endsection