routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('topics', 'TopicController');
Route::resource('questions', 'QuestionController');
Route::resource('results', 'ResultsController');
Route::resource('adminpanel', 'AdminPanelController');
Route::resource('questionsOptions', 'QuestionsOptionsController');
Route::resource('users', 'UserController');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    //

    protected $table = 'questions';

    public function options() {
        return $this->hasMany('App\Options', 'question_id', 'id');
    }

    public function correctOptionsCount() {
        return $this->options()->where('correct', 1 )->count();
    }

    public function correctOptions() {
       return  $this->options()->where('correct', 1)->get();
    }

    public function topic() {
        return $this->hasOne('App\Topic', 'id', 'topic_id');
    }

}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreQuestionRequest;
use App\Http\Requests\UpdateQuestionRequest;
use App\Options;
use App\Question;
use App\Topic;
use Illuminate\Http\Request;

class QuestionController extends Controller
{

    public function __construct() {
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $questions = Question::all();

        return view('questions.index', ['questions'=>$questions]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $topics = Topic::all();
        $question = Question::all();
        return view('questions.create',['question'=>$question, 'topics'=>$topics]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreQuestionRequest $request)
    {
        //
        $topicID = $request->input('topic');
        $questionText = $request->input('question');
        $optionArray = $request->input('options');
        $correctOptions = $request->input('correct');

        $question = new Question();
        $question->topic_id = $topicID;
        $question->question_text = $questionText;
        $question->save();

        $questionToAdd = Question::latest()->first();;
        $questionID = $questionToAdd->id;

        foreach ($optionArray as $index => $opt) {
            $option = new Options();
            $option->question_id = $questionID;
            $option->option = $opt;
            foreach ($correctOptions as $correctOption) {
                if($correctOption == $index+1) {
                    $option->correct = 1;
                }
            }

            $option->save();
        }
        $questionCount=Question::where('topic_id','=', $topicID)->count();
       
        $questionNumber=Topic::where('id', '=', $topicID)->value('no_question');
        if ($questionCount < $questionNumber ) {
            $examinfo = Topic::find($topicID);
            return redirect()->back();
        }else{
            $topics= Topic::all();
            session()->flash('error', 'No more questions');  
            return view('topics.index', ['question'=>$question, 'topics'=>$topics]);     }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)

    {
        //

        $question = Question::find($id);

        return view('questions.show', ['question'=>$question]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $question = Question::find($id);
        $topics = Topic::all();

        return view('questions.edit', ['question'=>$question, 'topics'=>$topics]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionRequest $request, $id)
    {
        //
        $topicID = $request->input('topic_id');
        $questionText = $request->input('question_text');

        $question = Question::find($id);
        $question->topic_id = $topicID;
        $question->question_text = $questionText;
        $question->save();


        return redirect(route('questions.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $question = Question::find($id);
        $question->delete();

        return redirect(route('questions.index'));

    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
<div class="form-group">

    <hr>
    <form action="{{route('questions.store')}}" method="post">
        @csrf
        <div class="table-responsive">
            <h2 class="mt-2" align="center">Add question to quiz</h2>
            <table class="table table-bordered" id="dynamic_field">
                <div class="form-group">
                    <label for="">Select Topic</label>
                    <select name="topic" id="inputState" class="form-control">
                        @foreach($topics as $topic)
                            <option selected value="{{$topic->id}}">{{$topic->title}}</option>
                        @endforeach
                    </select>
                </div>
                <tr>
                    <td>
                        <input type="text" name="question" placeholder="question"
                               class="form-control question_list" required
                        />
                    <td>
                        <input type="text" name="options[]" placeholder="option"
                               class="form-control options_list" required
                        />
                    </td>
                    <td>
                        <input type="checkbox"
                               name="correct[]"
                               value="1"
                               placeholder="correct"
                               class="form-control"
                        />
                    </td>

                    <td>
                        <button type="button" name="addAnswer" id="addAnswer" class="btn btn-success mb-2">
                            Add Answer
                        </button>
                    </td>
                </tr>
            </table>
            <input type="submit" name="addQuestion" id="addQuestion" class="btn btn-success mb-2 mr-2"
                   value="Add Question"/>
        </div>
    </form>
</div>
</div>
</div>


<script type="text/javascript">
$(document).ready(function () {
var n = 1;

$('#addAnswer').click(function () {
    n++;
    $('#dynamic_field').append('' +
        '<tr id="row' + n + '" class="dynamic-added">' +
        '<td>' +
        '</td>' +
        '<td>' +
        '<input type="text" name="options[]" required placeholder="option" class="form-control question_list" />' +
        '</td>' +
        '<td>' +
        '<input type="checkbox" name="correct[]" value="' + n + '" class="form-control question_list" />' +
        '</td>' +
        '<td>' +
        '<button type="button" name="remove" id="' + n + '" class="btn btn-danger btn_remove">X</button>' +
        '</td>' +
        '</tr>');
});


$(document).on('click', '.btn_remove', function () {
    var button_id = $(this).attr("id");
    $('#row' + button_id + '').remove();
});

});
</script>




@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            @if($question)
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" action="{{route('questions.update', $question->id)}}">
                    @csrf
                    @method('put')
                    <div class="panel panel-default">
                        <h2 align="center">Edit Question</h2>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <select class="form-control" name="topic_id">
                                        @foreach($topics as $topic)
                                            <option value="{{$topic->id}}" {{($topic->id == $question->topic_id) ? 'selected' : ''}}>{{$topic->title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="question_text" class="control-label">Question text</label>
                                    <textarea class="form-control" required placeholder="" name="question_text"
                                              cols="50"
                                              rows="10">{{$question->question_text}}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Update">
                </form>
            @else
                <h1>No Question</h1>
            @endif
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-4">
                    <h3 class="page-title">All Questions</h3>
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                        <tr>
                            <th>Topic</th>
                            <th>Question text</th>
                            <th>More</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($questions as $question)
                            <tr>
                                <td>
                                    @if($question->topic)
                                        {{$question->topic->title}}
                                    @endif
                                </td>
                                <td>
                                    @if(strlen($question->question_text) > 100)
                                        {{substr($question->question_text, 0, 100)}}...</td>
                                @else
                                    {{$question->question_text}}
                                @endif
                                <td>
                                    <a href="{{route('questions.show', $question->id)}}"
                                       class="btn btn-xs btn-primary">View</a>
                                    <a href="{{route('questions.edit', $question->id)}}"
                                       class="btn btn-xs btn-warning">Edit</a>
                                    <form class="inline_block" action="{{route('questions.destroy', $question->id)}}"
                                          method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            @if($question)
                <div class="row">
                    <div class="col-md-12 mt-4">
                        <h3 class="page-title">All Questions</h3>
                        <table class="table table-bordered table-striped datatable">
                            <thead>
                            <tr>
                                <th>Topic</th>
                                <th>Question text</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{$question->topic->title}}</td>
                                <td>{{$question->question_text}}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                <h1>No Question</h1>
            @endif
        </div>
    </div>
    </div>
@endsection