routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('topics', 'TopicController');
Route::resource('questions', 'QuestionController');
Route::resource('results', 'ResultsController');
Route::resource('adminpanel', 'AdminPanelController');
Route::resource('questionsOptions', 'QuestionsOptionsController');
Route::resource('users', 'UserController');

app/Http/Controllers/QuestionsOptionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateQuestionOptionsRequest;
use App\Options;
use App\Question;
use Illuminate\Http\Request;

class QuestionsOptionsController extends Controller
{

    public function __construct() {
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $options = Options::all();

        return view('questionsOptions.index', ['options'=>$options]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $option = Options::find($id);

        return view('questionsOptions.show', ['option'=>$option]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $questions = Question::all();
        $option = Options::find($id);

        return view('questionsOptions.edit', ['option'=>$option, 'questions'=>$questions]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionOptionsRequest $request, $id)
    {
        //

        $option = Options::find($id);

        $option->question_id = $request->input('question_id');
        $option->option = $request->input('option');
        $option->correct = $request->input('correct');
        $option->save();

        return redirect(route('questionsOptions.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $option = Options::find($id);
        $option->delete();

        return redirect(route('questionsOptions.index'));
    }
}

resources/views/questionsOptions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            @if($option)
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <h2 align="center">Edit Option</h2>
            <div class="form-group">
                <hr>
                <form action="{{route('questionsOptions.update', $option->id)}}" method="post">
                    @csrf
                    @method('put')
                    <div class="table-responsive">
                        <div class="form-group">
                            <select name="question_id" class="form-control">
                                @foreach($questions as $question)
                                    <option {{($option->question_id == $question->id) ? 'selected' : ''}} value="{{$question->id}}">{{$question->question_text}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                    <textarea required class="form-control options_list" name="option" id="" cols="30"
                              rows="10">{{$option->option}}</textarea>
                        </div>

                        <div>
                            Correct
                            <input type="checkbox"
                                   name="correct"
                                   value="1"
                                    {{($option->correct == 1) ? 'checked' : ''}}
                            />
                        </div>
                        <div class="mt-3">
                            <input class="btn btn-primary" type="submit" value="Update">
                        </div>
                    </div>
                </form>
            </div>
                @else
                    <h1>No Question Option</h1>
                @endif
        </div>
        </div>
    </div>
@endsection

resources/views/questionsOptions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-4">
                    <h3 class="page-title">All Options</h3>
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                        <tr>
                            <th>Question</th>
                            <th>Question option</th>
                            <th>Correct</th>
                            <th>More</th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($options as $option)
                            <tr>
                                    <td>
                                        @if($option->question)
                                        {{$option->question->question_text}}
                                        @endif
                                    </td>
                                <td>{{$option->option}}</td>
                                <td>
                                    @if($option->correct == 1)
                                        Yes
                                    @else
                                        No
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('questionsOptions.show', $option->id)}}"
                                       class="btn btn-xs btn-primary">View</a>
                                    <a href="{{route('questionsOptions.edit', $option->id)}}"
                                       class="btn btn-xs btn-warning">Edit</a>
                                    <form class="inline_block" action="{{route('questionsOptions.destroy', $option->id)}}"
                                          method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-xs btn-danger" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questionsOptions/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">
        @include('adminpanel.adminSidebar')
        <div class="container">
            @if($option)
            <div class="row">
                <div class="col-md-12 mt-4">
                    <h3 class="page-title">Option ID: {{$option->id}}</h3>
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                        <tr>
                            <th>Question</th>
                            <th>Question option</th>
                            <th>Correct</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                @if($option->question)
                                    {{$option->question->question_text}}
                                @endif
                            </td>
                            <td>{{$option->option}}</td>
                            <td>
                                @if($option->correct == 1)
                                    Yes
                                @else
                                    No
                                @endif
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            @else
                <h1>No Option</h1>
            @endif
        </div>
        </div>
    </div>
@endsection